development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://infinite-escarpment-51215.herokuapp.com:6379/1" } %>
  channel_prefix: Chat_production
